spring.datasource.url=jdbc:postgresql://workcalendar.cc9cka8eqwv9.us-east-1.rds.amazonaws.com:5432/workcalendar
spring.datasource.username=postgres
spring.datasource.password=Colombia#1823

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect